export const GET_CATEGORY_ID_START = "GET_CATEGORY_ID_START";
export const GET_CATEGORY_ID_SUCCESS = "GET_CATEGORY_ID_SUCCESS";
export const GET_CATEGORY_ID_FAILER = "GET_CATEGORY_ID_FAILER";

export const GET_CATEGORY_ALL_START = "GET_CATEGORY_ALL_START";
export const GET_CATEGORY_ALL_SUCCESS = "GET_CATEGORY_ALL_SUCCESS";
export const GET_CATEGORY_ALL_FAILER = "GET_CATEGORY_ALL_FAILER";

export const DELETE_CATEGORY_ID_START = "DELETE_CATEGORY_ID_START";
export const DELETE_CATEGORY_ID_SUCCESS = "DELETE_CATEGORY_ID_SUCCESS";
export const DELETE_CATEGORY_ID_FAILER = "DELETE_CATEGORY_ID_FAILER";

export const UPDATTE_CATEGORY_ID_START = "UPDATTE_CATEGORY_ID_START";
export const UPDATTE_CATEGORY_ID_SUCCESS = "UPDATTE_CATEGORY_ID_SUCCESS";
export const UPDATTE_CATEGORY_ID_FAILER = "UPDATTE_CATEGORY_ID_FAILER";

export const ADD_CATEGORY_START = "ADD_CATEGORY_START";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILER = "ADD_CATEGORY_FAILER";