export const GET_CATEGORY_ID_START = "GET_CATEGORY_ID_START";
export const GET_CATEGORY_ID_SUCCESS = "GET_CATEGORY_ID_SUCCESS";
export const GET_CATEGORY_ID_FAILER = "GET_CATEGORY_ID_FAILER";

export const GET_CATEGORY_ALL_START = "GET_CATEGORY_ALL_START";
export const GET_CATEGORY_ALL_SUCCESS = "GET_CATEGORY_ALL_SUCCESS";
export const GET_CATEGORY_ALL_FAILER = "GET_CATEGORY_ALL_FAILER";

export const DELETE_CATEGORY_ID_START = "DELETE_CATEGORY_ID_START";
export const DELETE_CATEGORY_ID_SUCCESS = "DELETE_CATEGORY_ID_SUCCESS";
export const DELETE_CATEGORY_ID_FAILER = "DELETE_CATEGORY_ID_FAILER";