export const GET_PRODUCTSIZE_ID_START = "GET_PRODUCTSIZE_ID_START";
export const GET_PRODUCTSIZE_ID_SUCCESS = "GET_PRODUCTSIZE_ID_SUCCESS";
export const GET_PRODUCTSIZE_ID_FAILER = "GET_PRODUCTSIZE_ID_FAILER";

export const GET_PRODUCTSIZE_ALL_START = "GET_PRODUCTSIZE_ALL_START";
export const GET_PRODUCTSIZE_ALL_SUCCESS = "GET_PRODUCTSIZE_ALL_SUCCESS";
export const GET_PRODUCTSIZE_ALL_FAILER = "GET_PRODUCTSIZE_ALL_FAILER";