export const GET_PRODUCT_ID_START = "GET_PRODUCT_ID_START";
export const GET_PRODUCT_ID_SUCCESS = "GET_PRODUCT_ID_SUCCESS";
export const GET_PRODUCT_ID_FAILER = "GET_PRODUCT_ID_FAILER";

export const GET_PRODUCT_ALL_START = "GET_PRODUCT_ALL_START";
export const GET_PRODUCT_ALL_SUCCESS = "GET_PRODUCT_ALL_SUCCESS";
export const GET_PRODUCT_ALL_FAILER = "GET_PRODUCT_ALL_FAILER";